name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build and publish
        run: ./gradlew publishToMavenLocal
