name: Android CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'simonnorberg/dmach-externals'
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build and publish
        run: ./gradlew publishToMavenLocal
